window.MUSICWAVE_CONFIG={
  youtubeApiKey:"PASTE_YOUTUBE_API_KEY",
  vkAccessToken:"PASTE_VK_ACCESS_TOKEN",
  vkApiVersion:"5.199",
  spotifyClientId:"PASTE_SPOTIFY_CLIENT_ID",
  spotifyRedirectUri:"https://YOUR_GITHUB_USERNAME.github.io/YOUR_REPO/",
  supabaseUrl:"https://YOUR_PROJECT.supabase.co",
  supabaseAnonKey:"PASTE_SUPABASE_ANON_KEY"
};