-- Run this in Supabase SQL Editor.
create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  title text not null,
  artist text,
  artwork text,
  url text,
  source text,
  created_at timestamptz default now(),
  unique(user_id,item_id)
);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  title text not null,
  artist text,
  artwork text,
  url text,
  source text,
  played_at timestamptz default now()
);

create table if not exists public.playlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz default now()
);

alter table public.favorites enable row level security;
alter table public.history enable row level security;
alter table public.playlists enable row level security;

create policy "own favorites select" on public.favorites for select using (auth.uid()=user_id);
create policy "own favorites insert" on public.favorites for insert with check (auth.uid()=user_id);
create policy "own favorites delete" on public.favorites for delete using (auth.uid()=user_id);

create policy "own history select" on public.history for select using (auth.uid()=user_id);
create policy "own history insert" on public.history for insert with check (auth.uid()=user_id);

create policy "own playlists all" on public.playlists for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
